#!/usr/bin/env bash
#
# Create the rig's config and disk image if they don't exist yet (issue #2).
#
# The config is deliberately self-contained: own socket, own NVRAM, own serial
# log and own disk. The media are the four IRIX 6.5.7 install discs in changer
# order on SCSI ID 4 (the bootable Installation Tools + Overlays disc first).
# SCSI ID 2 is the CI scratch volume, which `iris-ci put`/`get` address as
# /dev/rdsk/dks0d2s0 in the guest. The MAC is distinct from any other emulator
# instance on this host.
#
# Usage: scripts/rig/new-rig.sh [--disk-mb N]
#
set -euo pipefail

# shellcheck source=scripts/rig/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

usage() {
	cat <<'EOF'
Usage: scripts/rig/new-rig.sh [--disk-mb N]

  --disk-mb N  boot disk size in MB (default 20480)
  -h, --help   show this help
EOF
}

disk_mb=20480
while [ $# -gt 0 ]; do
	case "$1" in
		--disk-mb) disk_mb=$2; shift 2 ;;
		-h|--help) usage; exit 0 ;;
		*) rig_die "unknown option: $1 (try --help)" ;;
	esac
done

mkdir -p "$RIG_MEDIA_DIR" "$RIG_LOG_DIR" "$RIG_STATE_DIR" "$(dirname "$RIG_DISK")"

missing=()
for disc in "${RIG_INSTALL_MEDIA[@]}"; do
	[ -f "$RIG_MEDIA_DIR/$disc" ] || missing+=("$disc")
done
if [ "${#missing[@]}" -gt 0 ]; then
	printf 'rig: install media missing from %s:\n' "$RIG_MEDIA_DIR" >&2
	printf '  %s\n' "${missing[@]}" >&2
	rig_die "copy the IRIX 6.5.7 installation/foundation/overlays ISOs there"
fi

if [ ! -f "$RIG_CONFIG" ]; then
	rig_log "writing $RIG_CONFIG"
	cat >"$RIG_CONFIG" <<EOF
# Independent IRIX 6.5.7m rig (issue #2). Generated by scripts/rig/new-rig.sh.

headless   = false
no_audio   = true
banks      = [128, 128, 0, 0]
ci_socket  = "$RIG_SOCKET"
nvram      = "$RIG_NVRAM"
serial_log = "$RIG_SERIAL_LOG"

[machine]
cpu = "r4400"

[scsi.1]
path  = "$RIG_DISK"
cdrom = false

[scsi.2]
path     = "$RIG_SCRATCH"
scratch  = true
size_mb  = 64

[scsi.4]
path = "$RIG_MEDIA_DIR/${RIG_MEDIA_TOOLS_OVERLAYS_1}"
cdrom = true
discs = [
  "$RIG_MEDIA_DIR/${RIG_MEDIA_TOOLS_OVERLAYS_1}",
  "$RIG_MEDIA_DIR/${RIG_MEDIA_FOUNDATION_1}",
  "$RIG_MEDIA_DIR/${RIG_MEDIA_FOUNDATION_2}",
  "$RIG_MEDIA_DIR/${RIG_MEDIA_OVERLAYS_2}",
]

[network]
mac = "08:00:69:57:07:01"
EOF
fi

if [ ! -f "$RIG_DISK" ]; then
	rig_log "creating ${disk_mb}MB sparse disk $RIG_DISK"
	truncate -s "${disk_mb}M" "$RIG_DISK"
fi

rig_log "rig ready: $RIG_DIR"
